annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bumped helm dependency for mysql to 9.23.0
apiVersion: v2
appVersion: 3.7.4
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 16.5.0
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.23.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 14.1.3
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.14.0
description: A PHP-based self-hosted URL shortener that can be used to serve shortened
  URLs under your own domain.
home: https://github.com/christianhuth/helm-charts
icon: https://shlink.io/images/shlink-logo-blue.svg
maintainers:
- email: christian@knell.it
  name: christianhuth
name: shlink
sources:
- https://github.com/shlinkio/shlink
- https://shlink.io
type: application
version: 4.4.0
